export const languages = [
    {value: 'plaintext', text: 'Plain Text'},
    {value: 'abap', text: 'ABAP'},
    {value: 'apex', text: 'Apex'},
    {value: 'azcli', text: 'Azure CLI'},
    {value: 'bat', text: 'Batch'},
    {value: 'bicep', text: 'Bicep'},
    {value: 'cameligo', text: 'Cameligo'},
    {value: 'clojure', text: 'Clojure'},
    {value: 'coffeescript', text: 'CoffeeScript'},
    {value: 'c', text: 'C'},
    {value: 'cpp', text: 'C++'},
    {value: 'csharp', text: 'C#'},
    {value: 'csp', text: 'CSP'},
    {value: 'css', text: 'CSS'},
    {value: 'cypher', text: 'Cypher'},
    {value: 'dart', text: 'Dart'},
    {value: 'dockerfile', text: 'Dockerfile'},
    {value: 'ecl', text: 'ECL'},
    {value: 'elixir', text: 'Elixir'},
    {value: 'flow9', text: 'Flow9'},
    {value: 'fsharp', text: 'F#'},
    {value: 'freemarker2', text: 'Freemarker2'},
    {value: 'freemarker2.tag-angle.interpolation-dollar', text: 'Freemarker2 Angle $'},
    {value: 'freemarker2.tag-bracket.interpolation-dollar', text: 'Freemarker2 Bracket $'},
    {value: 'freemarker2.tag-angle.interpolation-bracket', text: 'Freemarker2 Angle [ ]'},
    {value: 'freemarker2.tag-bracket.interpolation-bracket', text: 'Freemarker2 Bracket [ ]'},
    {value: 'freemarker2.tag-auto.interpolation-dollar', text: 'Freemarker2 Auto $'},
    {value: 'freemarker2.tag-auto.interpolation-bracket', text: 'Freemarker2 Auto [ ]'},
    {value: 'go', text: 'Go'},
    {value: 'graphql', text: 'GraphQL'},
    {value: 'handlebars', text: 'Handlebars'},
    {value: 'hcl', text: 'HCL'},
    {value: 'html', text: 'HTML'},
    {value: 'ini', text: 'INI'},
    {value: 'java', text: 'Java'},
    {value: 'javascript', text: 'JavaScript'},
    {value: 'julia', text: 'Julia'},
    {value: 'kotlin', text: 'Kotlin'},
    {value: 'less', text: 'Less'},
    {value: 'lexon', text: 'Lexon'},
    {value: 'lua', text: 'Lua'},
    {value: 'liquid', text: 'Liquid'},
    {value: 'm3', text: 'M3'},
    {value: 'markdown', text: 'Markdown'},
    {value: 'mdx', text: 'MDX'},
    {value: 'mips', text: 'MIPS'},
    {value: 'msdax', text: 'MSDAX'},
    {value: 'mysql', text: 'MySQL'},
    {value: 'objective-c', text: 'Objective-C'},
    {value: 'pascal', text: 'Pascal'},
    {value: 'pascaligo', text: 'Pascaligo'},
    {value: 'perl', text: 'Perl'},
    {value: 'pgsql', text: 'PostgreSQL'},
    {value: 'php', text: 'PHP'},
    {value: 'pla', text: 'PLA'},
    {value: 'postiats', text: 'Postiats'},
    {value: 'powerquery', text: 'Power Query'},
    {value: 'powershell', text: 'PowerShell'},
    {value: 'proto', text: 'Protocol Buffers'},
    {value: 'pug', text: 'Pug'},
    {value: 'python', text: 'Python'},
    {value: 'qsharp', text: 'Q#'},
    {value: 'r', text: 'R'},
    {value: 'razor', text: 'Razor'},
    {value: 'redis', text: 'Redis'},
    {value: 'redshift', text: 'Redshift'},
    {value: 'restructuredtext', text: 'reStructuredText'},
    {value: 'ruby', text: 'Ruby'},
    {value: 'rust', text: 'Rust'},
    {value: 'sb', text: 'Small Basic'},
    {value: 'scala', text: 'Scala'},
    {value: 'scheme', text: 'Scheme'},
    {value: 'scss', text: 'SCSS'},
    {value: 'shell', text: 'Shell Script'},
    {value: 'sol', text: 'Solidity'},
    {value: 'aes', text: 'AES'},
    {value: 'sparql', text: 'SPARQL'},
    {value: 'sql', text: 'SQL'},
    {value: 'st', text: 'Structured Text'},
    {value: 'swift', text: 'Swift'},
    {value: 'systemverilog', text: 'SystemVerilog'},
    {value: 'verilog', text: 'Verilog'},
    {value: 'tcl', text: 'Tcl'},
    {value: 'twig', text: 'Twig'},
    {value: 'typescript', text: 'TypeScript'},
    {value: 'typespec', text: 'TypeSpec'},
    {value: 'vb', text: 'Visual Basic'},
    {value: 'wgsl', text: 'WGSL'},
    {value: 'xml', text: 'XML'},
    {value: 'yaml', text: 'YAML'},
    {value: 'json', text: 'JSON'},
];